version: '3'

services:
  app:
    build: .
    container_name: workshop03-app
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres:11
    container_name: workshop03-database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: